# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe850bdae968b19f74379b305db231fb5fc69833203381d51c2a9699ef476472e506ebc80b36780c27405bc53dc9909c6a111f9e3d593329829b1e7e5c35c406

test:
  secret_key_base: 5233dd94db50892ab62a149c032b2b3d9879c7d0c08f999ebaab4f8e5edb0c096954c24c2dcb95e1e8147c77ac758f6092b2da441054df164ae93ed5dafc5040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
